import Link from "next/link";
import type { AdminOrder } from "@/lib/services/admin-metrics-service";
import { StatusBadge } from "@/components/shared/status-badge";
import { currencyFormatter, dateTimeFormatter, paymentLabels } from "@/components/shared/formatters";

export function LiveOrdersTable({ orders }: { orders: AdminOrder[] }) {
  return <section className="premium-card overflow-hidden rounded-2xl" aria-labelledby="orders-title"><div className="flex items-center justify-between border-b border-zinc-100 px-4 py-4 sm:px-6"><div><h2 id="orders-title" className="text-lg font-black">Danh sách đơn hàng mới nhất</h2><p className="text-xs text-zinc-400">Tự động cập nhật trực tuyến</p></div><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-bold text-emerald-700">● Live</span></div>
    {orders.length === 0 ? <p className="p-10 text-center text-sm text-zinc-400">Chưa có đơn hàng nào — đơn mới từ Messenger sẽ hiện tại đây.</p> : <>
    <div className="divide-y divide-zinc-100 md:hidden">{orders.map((order) => <article key={order.id} className="p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-mono text-sm font-black" translate="no">{order.id}</p><time className="mt-0.5 block text-[11px] text-zinc-400" dateTime={order.createdAt}>{dateTimeFormatter.format(new Date(order.createdAt))}</time>{order.storeName ? <p className="mt-0.5 text-[11px] font-semibold text-zinc-500">{order.storeName}</p> : null}</div><StatusBadge status={order.status} /></div><div className="mt-4 grid grid-cols-2 gap-3 rounded-xl bg-zinc-50 p-3"><div><p className="text-[10px] font-bold uppercase tracking-wider text-zinc-400">Thanh toán</p><p className="mt-1 text-xs font-bold text-zinc-700">{order.paymentMethod ? paymentLabels[order.paymentMethod] : "Chưa chọn"}</p></div><div className="text-right"><p className="text-[10px] font-bold uppercase tracking-wider text-zinc-400">Tổng thanh toán</p><p className="mt-1 text-sm font-black tabular-nums">{currencyFormatter.format(order.totalVnd)}</p></div><div><p className="text-[10px] font-bold uppercase tracking-wider text-zinc-400">Số lượng món</p><p className="mt-1 text-xs font-bold text-zinc-700">{order.items.reduce((sum, item) => sum + item.quantity, 0)} món</p></div><div className="text-right"><p className="text-[10px] font-bold uppercase tracking-wider text-zinc-400">Gợi ý AI (Upsell)</p><p className={`mt-1 text-xs font-bold ${order.upsellAccepted ? "text-emerald-700" : "text-zinc-500"}`}>{order.upsellAccepted ? "Đồng ý" : "Không áp dụng"}</p></div></div><Link href={`/order/${order.id}`} className="pressable mt-3 block rounded-xl border border-zinc-200 bg-white px-4 py-3 text-center text-sm font-black text-red-700 hover:border-red-200 hover:bg-red-50 focus-visible:ring-2 focus-visible:ring-red-600">Theo dõi đơn hàng →</Link></article>)}</div>
    <div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[820px] text-left text-sm"><thead className="bg-zinc-50 text-[11px] uppercase tracking-wider text-zinc-400"><tr><th className="px-6 py-3 font-bold">Mã đơn hàng</th><th className="px-4 py-3 font-bold">Trạng thái</th><th className="px-4 py-3 font-bold">Cửa hàng</th><th className="px-4 py-3 font-bold">Phương thức</th><th className="px-4 py-3 font-bold">Gợi ý AI</th><th className="px-4 py-3 text-right font-bold">Tổng thanh toán</th><th className="px-6 py-3 text-right font-bold">Thao tác</th></tr></thead><tbody className="divide-y divide-zinc-100">{orders.map((order) => <tr key={order.id} className="transition-colors duration-200 hover:bg-zinc-50"><td className="px-6 py-4"><p className="font-mono font-black" translate="no">{order.id}</p><time className="text-xs text-zinc-400" dateTime={order.createdAt}>{dateTimeFormatter.format(new Date(order.createdAt))}</time></td><td className="px-4 py-4"><StatusBadge status={order.status} /></td><td className="px-4 py-4 text-xs font-semibold text-zinc-600">{order.storeName ?? "—"}</td><td className="px-4 py-4 font-semibold text-zinc-600">{order.paymentMethod ? paymentLabels[order.paymentMethod] : "Chưa chọn"}</td><td className="px-4 py-4"><span className={order.upsellAccepted ? "font-bold text-emerald-700" : "text-zinc-400"}>{order.upsellAccepted ? "Đồng ý" : "—"}</span></td><td className="px-4 py-4 text-right font-black tabular-nums">{currencyFormatter.format(order.totalVnd)}</td><td className="px-6 py-4 text-right"><Link href={`/order/${order.id}`} className="rounded-lg px-3 py-2 text-xs font-black text-red-700 hover:bg-red-50 focus-visible:ring-2 focus-visible:ring-red-600">Theo dõi →</Link></td></tr>)}</tbody></table></div>
    </>}
  </section>;
}
