import type { AdminMetrics } from "@/lib/mock/mock-data-types";
import { currencyFormatter } from "@/components/shared/formatters";

const cardBase = "premium-card pressable min-w-0 w-full overflow-hidden rounded-2xl p-5 sm:p-6 hover:shadow-[0_16px_45px_rgb(24_24_27_/_0.08)]";

export function MetricCards({ metrics }: { metrics: AdminMetrics }) {
  const conversion = Math.round((metrics.funnel.delivered / metrics.funnel.conversationsStarted) * 100);
  const nluRate = Math.round((metrics.nluEval.passed / metrics.nluEval.total) * 100);
  return <div className="grid w-full min-w-0 grid-cols-1 gap-3 sm:grid-cols-2 sm:gap-5 xl:grid-cols-4">
    <article className="pressable min-w-0 w-full overflow-hidden rounded-2xl bg-gradient-to-br from-zinc-950 to-zinc-800 p-5 text-white shadow-[0_16px_45px_rgb(24_24_27_/_0.18)] hover:shadow-[0_20px_55px_rgb(24_24_27_/_0.24)] sm:p-6"><div className="flex items-center justify-between"><p className="text-xs font-bold uppercase tracking-[0.15em] text-zinc-400">Tỷ lệ chuyển đổi</p><span className="text-emerald-400" aria-hidden="true">↗</span></div><p className="mt-8 text-4xl font-black tabular-nums">{conversion}%</p><p className="mt-1 text-sm text-zinc-400">Hội thoại chuyển đổi thành đơn hàng</p><div className="mt-6 h-1.5 overflow-hidden rounded-full bg-zinc-700"><div className="h-full rounded-full bg-gradient-to-r from-red-600 to-orange-400" style={{ width: `${conversion}%` }} /></div></article>
    <article className={`${cardBase} hover:border-red-200`}><p className="text-xs font-bold uppercase tracking-[0.15em] text-zinc-400">AOV sau Upsell</p><p className="mt-8 text-3xl font-black tabular-nums">{currencyFormatter.format(metrics.aov.withUpsellVnd)}</p><p className="mt-1 text-sm font-bold text-emerald-700">Tăng trưởng +{metrics.aov.upliftPct}%</p><p className="mt-5 text-xs text-zinc-400">Giá trị gốc: {currencyFormatter.format(metrics.aov.withoutUpsellVnd)}</p></article>
    <article className={`${cardBase} hover:border-amber-200`}><p className="text-xs font-bold uppercase tracking-[0.15em] text-zinc-400">Tỷ lệ đồng ý gợi ý món</p><p className="mt-8 text-4xl font-black tabular-nums">{metrics.upsell.acceptanceRatePct}%</p><p className="mt-1 text-sm text-zinc-500"><strong className="text-zinc-800">{metrics.upsell.accepted}</strong> / {metrics.upsell.offered} đơn hàng được gợi ý</p><div className="mt-6 h-1.5 overflow-hidden rounded-full bg-zinc-100"><div className="h-full rounded-full bg-gradient-to-r from-amber-500 to-orange-400" style={{ width: `${metrics.upsell.acceptanceRatePct}%` }} /></div></article>
    <article className={`${cardBase} hover:border-emerald-200`}><div className="flex items-center justify-between"><p className="text-xs font-bold uppercase tracking-[0.15em] text-zinc-400">Độ hiểu ý khách (NLU)</p><span className="rounded-full bg-emerald-50 px-2 py-1 text-[10px] font-black text-emerald-700">ĐẠT</span></div><p className="mt-8 text-4xl font-black tabular-nums">{metrics.nluEval.passed}<span className="text-xl text-zinc-300">/{metrics.nluEval.total}</span></p><p className="mt-1 text-sm text-zinc-500">Độ chính xác phân tích NLU {nluRate}%</p><p className="mt-5 truncate text-xs text-zinc-400" title={metrics.nluEval.comment}>{metrics.nluEval.comment}</p></article>
  </div>;
}
